### ISSUE TITLE
v440-owl file path returns 404

### ISSUE THREAD

**Issue by SigveMartin** [buildingsmart-norway/maskinlesbar_v440#1]
I tried accessing the owl file as referenced in the wiki documentation; 

>v440-brudata-owl.ttl importerar följande ontologier:
>http://rdf.vegdata.no/v440-owl (v440)

The url returns a 404 not found error when trying to access with browser. 

@larswik is this not supposed to return the documentation? Haven't tried requesting the rdf/ttl.

**Comment by larswik** [comment]
Yees it is. It worked a couple of days ago but I also get a 404 now? @iSkogli ??

**Comment by larswik** [comment]
Rätt uri ska vara http://rdf.vegdata.no/V440/v440-owl

**Comment by SigveMartin** [comment]
@larswik have to correct it before resolving ;-) Did it now.
