### ISSUE TITLE
Byggverkskategorier - Bru i dagen

### ISSUE THREAD

**Issue by hkgrani** [buildingsmart-norway/maskinlesbar_v440#12]
I onlologien "grupperes" tre av kategoriene under noden "ordinær bru i dagen", mens i nummereringen og slik vi leser v440 ser det mer ut som en flat liste. Når vi gjør spørringer får vi alle kategoriene og kan velge å lage flat liste eller kopiere undernoden. hva er rett?

<img width="280" alt="v440-owl__http___rdf_vegdata_no_V440_v440-owl______http___rdf_vegdata_no_V440_v440-owl_ttl_" src="https://user-images.githubusercontent.com/1169681/81549760-89c8f680-937f-11ea-80fe-a66473c6a789.png">

<img width="317" alt="Hb-V440_pdf__page_18_of_210_" src="https://user-images.githubusercontent.com/1169681/81549834-a6652e80-937f-11ea-84c3-a07cc9ab861e.png">

**Comment by larswik** [comment]
Anledningen att jag lade dit "Ordinar_bru_i_dagen" var att handboken specificerar ett antal properties som gäller Vegbru, Jernbanebru och Gang- og sykkelvegbru. 
![image](https://user-images.githubusercontent.com/25506404/81555338-b59caa00-9388-11ea-8304-d9ce08ffa445.png)

Jag ville lägga in dessa properties på ett ställe och då blev det enklast att göra en gemensam basklass. Jag har inga synpunkter på hur detta presenteras men om detta blir opraktiskt så måste ni säga till.

**Comment by hkgrani** [comment]
Det fungerer egentlig helt greit. Jeg fikk god forklaring både i workshop og her. Og for sparql spørringen så kommer det som flat liste uansett.
Så ta det mer som et innpill på at jeg som nybegynner ble litt forvirret når jeg så dataene i protegé.
Så ikke noe problem for oss at det er slik det står nå. Logger her hvis jeg finner tilsvarende, men saken kan gjerne lukkes for vår del
