### ISSUE TITLE
Alternativ ifc fil med IfcClassification.Reference

### ISSUE THREAD

**Issue by olekvarsvik** [buildingsmart-norway/maskinlesbar_v440#15]
Vi trøbler med å lese den klassifiserte ifc filen. Er det noen som kan bidra med en alternativ fil som inneholder IfcClassification.Reference?

**Comment by SigveMartin** [comment]
Det hadde vært kult om noen av de som har klassifisert og skrevet til IFC kunne delt modeller. 

@espenshi dere hadde vel en fil klassifisert?

**Comment by espenshi** [comment]
Jeg har laget en pull request for å legge til filene jeg genererte på første arbeidsmøte. Det er en som er klassifisert, og en som ikke er klassifisert. 
Jeg håper de kan være til hjelp.

**Comment by SigveMartin** [comment]
Nydelig, tusen takk!

tor. 14. mai 2020, 16:15 skrev Espen <notifications@github.com>:

**Comment by SigveMartin** [comment]
Pull requesten er merget inn i master nå, så da finner dere filene fra @espenshi under modellfiler. 

Lukker saken, men andre som ønsker å bidra med filer kan veldig gjerne følge @espenshi sitt eksempel 👍 

@olekvarsvik sjekk ut modellfiler :-)

**Comment by olekvarsvik** [comment]
Som mannen sa, "Nydelig"! Jeg tester filene :-)
