### ISSUE TITLE
SPARQL for å bygge Klassehierarki

### ISSUE THREAD

**Issue by hkgrani** [buildingsmart-norway/maskinlesbar_v440#17]
Bare et lite spørsmål for å sjekke hva som er mest "effektiv"/ "korrekt" måte å bygge klassehierarkiet / klassgrafen på ved bruk av SPARQL.

For den initielle implementasjonen vår har vi utvidet denne spørringen....
https://github.com/buildingsmart-norway/maskinlesbar_v440/wiki/02-Tilgang-til-ontologien#alla-klasser-som-%C3%A4r-byggverk-alla-niv%C3%A5er---f%C3%B6r-endast-f%C3%B6rsta-niv%C3%A5n-ta-bort-

Til å inkludere "subclassOf" på denne måten

```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix onto: <http://www.ontotext.com/>
prefix v440: <http://rdf.vegdata.no/V440/v440-owl#>
prefix v440bd: <http://rdf.vegdata.no/V440/v440-brudata-owl#>
select distinct ?class ?code ?name ?subclass ?subname ?subcode
where
{
	?class rdfs:subClassOf+ v440:Byggverkselement .
	?class rdfs:label ?name .
	?class v440:kode ?code .
        ?subclass rdfs:subClassOf ?class .
        ?subclass rdfs:label ?subname .
	?subclass v440:kode ?subcode .
} 
```

Vi kan da bygge hierarkiet/ grafen derfra. Vi er imidlertid usikre på om dette er beste måte å gjøre spørringen på. Finnes det for eksempel mulighet til å spørre om "den inverse" av subClassOf (superClass of)? f. eks ? @larswik

**Comment by larswik** [comment]
Detta med (superClassOf) får man genom att vända på uttrycket. Om jag förstår frågan rätt så skulle jag ha skrivit på följande sätt:
```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix onto: <http://www.ontotext.com/>
prefix v440: <http://rdf.vegdata.no/V440/v440-owl#>
prefix v440bd: <http://rdf.vegdata.no/V440/v440-brudata-owl#>
select distinct ?class ?code ?name ?superclass ?supername ?supercode
where
{
    ?class rdfs:subClassOf+ v440:Byggverkselement .
    ?class rdfs:label ?name .
    ?class v440:kode ?code .
    ?class rdfs:subClassOf ?superclass .
    ?superclass a owl:Class .
    ?superclass rdfs:label ?supername .
    ?superclass v440:kode ?supercode .
} 

```
Viktigt att frågan ställs utan "reasoning" eftersom man annars får superklasser "hela vägen upp". 
Tyvärr upptäckte jag ett litet fel i ontologin där vissa klasser har fått flera koder vilket innebär att samma klass kommer i svaret flera gånger. Detta ska vi rätta till i ontologin (jag registrerar en separat issue för detta).

**Comment by hkgrani** [comment]
Flott. Takk for kjapt svar.

**Comment by larswik** [comment]
För att få det helt rätt skulle jag dessutom stoppa in några "OPTIONAL" i spörringen så att man inte råkar missa något som saknar label eller kode:
```
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix onto: <http://www.ontotext.com/>
prefix v440: <http://rdf.vegdata.no/V440/v440-owl#>
prefix v440bd: <http://rdf.vegdata.no/V440/v440-brudata-owl#>
select distinct ?class ?code ?name ?superclass ?supername ?supercode
where
{
	?class rdfs:subClassOf+ v440:Byggverkselement .
    OPTIONAL {?class rdfs:label ?name} 
    OPTIONAL {?class v440:kode ?code} 
    ?class rdfs:subClassOf ?superclass .
    ?superclass a owl:Class .
    OPTIONAL {?superclass rdfs:label ?supername} 
    OPTIONAL {?superclass v440:kode ?supercode} 
} 
```
