### ISSUE TITLE
Ingen respons fra host

### ISSUE THREAD

**Issue by thomasoestgulen** [buildingsmart-norway/maskinlesbar_v440#26]
Hei. Prøver å kjøre Python koden for å få lest V440 fra http://rdfspatial.vegdata.no:7200/repositories/V440 . 

Får ingen respons fra nettsiden. Er dataen flyttet? 

Feilmelding: 
`Exception has occurred: ConnectionError
HTTPConnectionPool(host='rdfspatial.vegdata.no', port=7200): Max retries exceeded with url: /repositories/V440?Accept=application%2Fjson&query=SELECT+%3Furi+%3Flabel%0A++++++++++++++++WHERE+%7B%0A++++++++++++++++%3Furi+rdfs%3Alabel+%3Flabel+.%0A++++++++++++++++FILTER%28%3Flabel%3D%22Underbygning%22%40no%29%0A++++++++++++++++%7D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05891478>: Failed to establish a new connection: [WinError 10060] Et tilkoblingsforsøk mislyktes fordi den tilkoblede parten ikke svarte på riktig måte etter en tidsperiode, eller den etablerte tilkoblingen mislyktes fordi den tilkoblede verten ikke svarte'))

During handling of the above exception, another exception occurred:

  
    print(get_v440_uris("Underbygning"))`

**Comment by SigveMartin** [comment]
Hei! Statens vegvesen har gjort noen endringer og klonet dette repoet til sin egen git her: https://git.vegvesen.no/projects/BOLC/repos/maskinlesbar_v440/browse

@simonherbert69 kan nok oppdatere på riktig endepunkt fot spørringer

**Comment by thomasoestgulen** [comment]
> Hei! Statens vegvesen har gjort noen endringer og klonet dette repoet til sin egen git her: https://git.vegvesen.no/projects/BOLC/repos/maskinlesbar_v440/browse
> 
> @simonherbert69 kan nok oppdatere på riktig endepunkt fot spørringer

Takk for raskt svar. Sjekker opp i det nye repoet.

**Comment by thomasoestgulen** [comment]
Var litt rask med å avslutte tråden her. Ligger inne samme sti på SVVs nye Git portal. Har ikke mulighet til å legge inn issus i den løsningen uten å logge inn(?) og får ikke logget inn uten SVV bruker.

**Comment by SigveMartin** [comment]
Ok, tror enten @Nordlenningen eller @simonherbert69 kan den nye urinen? 

@simonherbert69 dere bør jo ha en isdue tracker btw... 🙂

**Comment by Nordlenningen** [comment]
Alle ontologier er nå samlet her;
https://ontologi.atlas.vegvesen.no/

Repoene er forøvrig også på tur fra Github og over i SVV sin Bitbucket, usikker på status.

-B

**Comment by thomasoestgulen** [comment]
Takk @Nordlenningen . Har du noen formening om hva jeg bør bytte URL adressen i Python eksempelet til for å få den til å hente data?
 
`def get_v440_uris(label):
    url = "http://rdfspatial.vegdata.no:7200/repositories/V440"
    query ="""SELECT ?uri ?label
                WHERE {
                ?uri rdfs:label ?label .
                FILTER(?label="%s"@no)
                }"""%label
    r = requests.get(url, params = {"Accept": "application/json", 'query': query})
    return r.json()["results"]["bindings"]`

**Comment by Nordlenningen** [comment]
Har den lagret en plass, men ikke nå, nå er det Cupen og Bodø Glimt som gjelder. Men i morra (om det ikke brennhaster) 😄

**Comment by SigveMartin** [comment]
Prøv med https://ontologi.atlas.vegvesen.no/bridge/v440/core/v440-owl.ttl

søn. 20. mar. 2022, 21:28 skrev Bjørnar Markussen ***@***.***

**Comment by Nordlenningen** [comment]
Mente de drev og fiklet med noen endringer av adressen, men ser at; https://ontologi.atlas.vegvesen.no/bridge/v440/core/v440-owl.ttl 
svarer :-)

Si fra om du ikke kommer videre (heie Bodø Glimt...).

**Comment by ELIDAL** [comment]
Hei, Produkteier her.
Kan jeg be om at alle samhandler videre på [https://git.vegvesen.no/projects/BOLC] Her ligger både kildekoden til BOLC g utviklingen på V440 og V441.
Så får vi dokumentert fremtidige utfordringer der utviklingen nå skjer ellers. 
@SigveMartin @JanErikHoel  Dere skulle autodirigere fra disse githubsidene? til SVV-git?

**Comment by thomasoestgulen** [comment]
Hei @ELIDAL. 
Jeg prøvde å lage en sak på den nye git løsningen som du linker til, men har ikke bruker hos vegvesenet så får ikke logget inn, og det finnes ikke mulighet til å lage Issues uten innlogging.

**Comment by simonherbert69** [comment]
Beklager sent svar - Riktig Graphdb link er 

https://rdfmod.utv.vegvesen.no/sparql 

Og det er følgende ontologier som er lastet inn der , bortsett fra MMI.
https://ontologi.atlas.vegvesen.no/ (og usikker om siste versjoner er lastet opp i GraphDb på https://rdfmod.utv.vegvesen.no/sparql 



I tillegg må vi i BOLC/MOPS prosjektene tar en ny runde angående migrering av V440 og V441 fra Buildingsmarts sin GitHub, til  Statens Vegvesens sin BitBucket, hvor vi har en del "Public" repos, med ingen publicc kobling til jira/saks system.

Simon Herbert
Innleid løsningsarkitekt
Løsningsarkitektur
IT Utvikling
Statens Vegvesen.
mailto:simon.herbert@vegvesen.no
mailto:simon.herbert@communicte.no

**Comment by larswik** [comment]
Det verkar som att ontologi-URI:erna skulle behöva en liten uppdatering om man ska kunna använda dessa URI:er för direkt nedladdning:

T ex:
- https://ontologi.atlas.vegvesen.no/v440/core/v440-owl

hittas under:
- https://ontologi.atlas.vegvesen.no/bridge/v440/core/v440-owl.ttl

**Comment by simonherbert69** [comment]
> Beklager sent svar - Riktig Graphdb link er
> 
> https://rdfmod.utv.vegvesen.no/sparql
> 
> Og det er følgende ontologier som er lastet inn der , bortsett fra MMI. https://ontologi.atlas.vegvesen.no/ (og usikker om siste versjoner er lastet opp i GraphDb på https://rdfmod.utv.vegvesen.no/sparql
> 
> I tillegg må vi i BOLC/MOPS prosjektene tar en ny runde angående migrering av V440 og V441 fra Buildingsmarts sin GitHub, til Statens Vegvesens sin BitBucket, hvor vi har en del "Public" repos, med ingen publicc kobling til jira/saks system.
> 
> Simon Herbert Innleid løsningsarkitekt Løsningsarkitektur IT Utvikling Statens Vegvesen. mailto:[simon.herbert@vegvesen.no](mailto:simon.herbert@vegvesen.no) mailto:[simon.herbert@communicte.no](mailto:simon.herbert@communicte.no)

beklager, men den nye Graphdb ser ikke ut å være tilgjengelig til omverden :-( Jeg har nevnte dette før, og skal følgende det opp igjen.)

https://rdfmod.vegvesen.no/sparql  (produksjon)

https://rdfmod.utv.vegvesen.no/sparql (utvikling) vil i utgangspunkt bare være internt.

**Comment by Nordlenningen** [comment]
Respons GraphDB;
«Connection timed out»


Med vennlig hilsen
Bjørnar Markussen

[AAJ_logo]
Dr. Ing. A. Aas-Jakobsen AS
Lilleakerveien 4A, inngang 2, 0283 Oslo
| Sentralbord: +47 22 51 30 00  |  Mobil:+47 95 13 85 02 |
| E-post: ***@***.******@***.***> | Webside: www.aaj.no<http://www.aaj.no> |

Fra: Simon Herbert ***@***.***>
Sendt: mandag 21. mars 2022 12:45
Til: buildingsmart-norway/maskinlesbar_v440 ***@***.***>
Kopi: Bjørnar Markussen ***@***.***>; Mention ***@***.***>
Emne: Re: [buildingsmart-norway/maskinlesbar_v440] Ingen respons fra host (Issue #26)


Beklager sent svar - Riktig Graphdb link er

https://rdfmod.utv.vegvesen.no/sparql<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frdfmod.utv.vegvesen.no%2Fsparql&data=04%7C01%7Cbma%40aaj.no%7C95d2e238bb2e487a33cf08da0b3036cf%7C38eda567e1174920b7a13cc7c74cf11b%7C0%7C0%7C637834598959401962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZuE7eU0%2BMjG1yDsiRUvklbia3jWAVa5Su0OUwW%2B6i8s%3D&reserved=0>

Og det er følgende ontologier som er lastet inn der , bortsett fra MMI.
https://ontologi.atlas.vegvesen.no/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fontologi.atlas.vegvesen.no%2F&data=04%7C01%7Cbma%40aaj.no%7C95d2e238bb2e487a33cf08da0b3036cf%7C38eda567e1174920b7a13cc7c74cf11b%7C0%7C0%7C637834598959401962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6B11qoGTpBmxE%2Bh%2FG7fTmFouVsAocrQRUvGwdeFMFGU%3D&reserved=0> (og usikker om siste versjoner er lastet opp i GraphDb på https://rdfmod.utv.vegvesen.no/sparql<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frdfmod.utv.vegvesen.no%2Fsparql&data=04%7C01%7Cbma%40aaj.no%7C95d2e238bb2e487a33cf08da0b3036cf%7C38eda567e1174920b7a13cc7c74cf11b%7C0%7C0%7C637834598959558196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EiFNKQZ7gsJr%2FmZHnNwZpaLSdEb8B8ASNLt6GuurjPQ%3D&reserved=0>

I tillegg må vi i BOLC/MOPS prosjektene tar en ny runde angående migrering av V440 og V441 fra Buildingsmarts sin GitHub, til Statens Vegvesens sin BitBucket, hvor vi har en del "Public" repos, med ingen publicc kobling til jira/saks system.

Simon Herbert
Innleid løsningsarkitekt
Løsningsarkitektur
IT Utvikling
Statens Vegvesen.
***@***.******@***.***>
***@***.******@***.***>

-

**Comment by simonherbert69** [comment]
Better late than never.

Da er https://rdfmod.vegvesen.no/ tilgjengelig på internettet.
Følgende ontoliges er lastet inn - https://ontologi.atlas.vegvesen.no/ 

NB: vi har ikke fått rettet opp alle linker i v440 osv.... - ligger i jira som TODO.

Bare send en mail til mailto:simon.herbert@evidi.com eller mailto:simon.herbert@vegvesen.no
