### ISSUE TITLE
IFC-fil for klassifisering

### ISSUE THREAD

**Issue by Nordlenningen** [buildingsmart-norway/maskinlesbar_v440#4]
Storbruen er klar for klassifisering. Eksempelmodellen er fjernet.

**Comment by SigveMartin** [comment]
første fil klassifisert og pushet. Skal sjekke over i morgen

**Comment by SigveMartin** [comment]
Har klassifisert bruen med v440 koder. Script ligger i repo. Fil ligger her: https://github.com/buildingsmart-norway/maskinlesbar_v440/tree/master/modellfiler

Sjekker du @Nordlenningen ?
