### ISSUE TITLE
Får ikke klonet

### ISSUE THREAD

**Issue by kriskal92** [buildingsmart-norway/maskinlesbar_v440#5]
Får feilmelding fra github:
error: invalid path 'Presentations/[openLAB : Interoperate] Intromøte/README.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

Noen tips?

**Comment by SigveMartin** [comment]
Forsøk nå. Jeg har tatt bort [, ] og : i mappenavnet.

**Comment by SigveMartin** [comment]
Melder du tilbake når du får testet igjen @kriskal92 ?

**Comment by kriskal92** [comment]
Ja, testet nå og det fungerer fint :)

**Comment by SigveMartin** [comment]
Flott!

Konge å se du er igang :-)

tir. 17. mar. 2020, 12:45 skrev kriskal92 <notifications@github.com>:
