### ISSUE TITLE
Annotation property v440:kapitel > v440 kapittel ?

### ISSUE THREAD

**Issue by hkgrani** [buildingsmart-norway/maskinlesbar_v440#6]
Ser ut som det har sneket seg inn et svenskt begrep her. Bør være norsk (eller engelsk?)

Eventuelt kanskje dette er en del av den nordiske harmoniseringen.

Uansett logger som issue/ spørsmål til @larswik 

http://rdf.vegdata.no/V440/v440-doc/v440-owl-doc/index.html#kapitel

**Comment by hkgrani** [comment]
Vil dere vi skal "assigne" til de vi tror bør plukke det opp @SigveMartin ? Eller vil dere styre det selv? Har foreløpig kun mentioned Lars som jeg tror er rett adressat

**Comment by larswik** [comment]
Oops.. Nice spotted. Lätt hänt med en svensk editor.  Detta är lätt åtgärdat, men vi kanske ska ta en snabb diskussion eftersom det nog finns möjlighet att flera liknande fel kommer att upptäckas.

**Comment by SigveMartin** [comment]
Tenker det er flott om vi samler slike innspill i issues slik som dette.

Så tar vi en runde og oppdaterer og løser dem i en bulk i noen release
sykluser. Så får vi samlet feedback.

Velsig bra du bruker issues slik HK!

tor. 19. mar. 2020, 10:35 skrev larswik <notifications@github.com>:

**Comment by hkgrani** [comment]
Ikke noe problem å leve med dette i denne fasen. Jeg tenker vi må balansere ønsket om å "så tidlig som mulig få rett ontologi" med ønske om "så få som mulig endringer underveis"

Vi kan godt bruke det vi har nå og samle opp disse endringene til slutten av denne fasen. Eventuelt kan en gjøre en kjapp språksjekk og gjøre en kjapp release på feilene en finner.

Me vi må uansett ta høyde for at det kommer endringer så ikke så viktig. 

Så kommentaren til @SigveMartin når jeg hadde skrevet. Enig i hans kommentar!

**Comment by SigveMartin** [comment]
Kan godt Assigne. På slike modellering og ontologi saker kan du Assigne til Lars. 

Jeg følger og får med meg alle issues, men flott å bruke "@" slik u gjør over.

**Comment by larswik** [comment]
Nu ska denna vara åtgärdad.
