### ISSUE TITLE
Support for https

### ISSUE THREAD

**Issue by palktonderAtpowelno** [buildingsmart-norway/maskinlesbar_v440#7]
It seems like the http://rdf.vegdata.no/V440/v440-doc/v440-owl-doc/ site doesn't support https. This can become an issue if it's called from a site already using https, since it can be perceived as a security risk. Ideally, the site should support both

**Comment by SigveMartin** [comment]
Thanks for the feedback! That is on the Road Authorities' side. There will anyways be changes to the sparql endpoint going into ops (still in dev/test). 

@iSkogli could you look into possibilities of supporting https for the sparql endpoint during testing?

**Comment by iSkogli** [comment]
Https now supported.

**Comment by SigveMartin** [comment]
@palktonderAtpowelno at this stage we will make the rdf.vegdata.no endpoint available for both http and https. The resources will still only be identified using http IRIs for the duration of this [openLAB : Interoperate] test stage. 

When going towards an operation environment this will be revisited.
